[project]
name = "inflationforecasting"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.10",
    "ipykernel>=7.4.0",
    "lightgbm>=4.7.0",
    "nbclient>=0.11.0",
    "nbformat>=5.11.1",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "rapidfuzz>=3.14.6",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
    "xgboost>=3.4.1",
    "yfinance>=1.7.0",
]
